export const bakedGoodsTreatsCategory = [ 

{id: "bt1", emoji: "🥐", wordJP:"いぬ"},
{id: "bt2", emoji: "🥯", wordJP:"ねこ"},
{id: "bt3", emoji: "🍞", wordJP:"ネズミ"},
{id: "bt4", emoji: "🥖", wordJP:"ハムスター"},
{id: "bt5", emoji: "🥨", wordJP:"ウサギ"},
{id: "bt6", emoji: "🥠", wordJP:"キツネ"},
{id: "bt7", emoji: "🥮", wordJP:"くま"},
{id: "bt8", emoji: "🍢", wordJP:"パンダ"},
{id: "bt9", emoji: "🍡", wordJP:"コアラ"},
{id: "bt10", emoji: "🍧", wordJP:"とら"},
{id: "bt11", emoji: "🍨", wordJP:"ライオン"},
{id: "bt12", emoji: "🍦", wordJP:"うし"},
{id: "bt13", emoji: "🥧", wordJP:"ライオン"},
{id: "bt14", emoji: "🧁", wordJP:"かえる"},
{id: "bt15", emoji: "🍰", wordJP:"さる"},
{id: "bt16", emoji: "🎂", wordJP:"こうもり"},
{id: "bt17", emoji: "🍮", wordJP:"おおかみ"},
{id: "bt18", emoji: "🍭", wordJP:"いのしし"},
{id: "bt19", emoji: "🍬", wordJP:"うま"},
{id: "bt20", emoji: "🍫", wordJP:"かわうそ"},
{id: "bt21", emoji: "🍿", wordJP:"やまあらし"},
{id: "bt22", emoji: "🍘", wordJP:"ぞう"},
{id: "bt23", emoji: "🥕", wordJP:"ぞう"},
{id: "bt24", emoji: "🧄", wordJP:"ぞう"},
{id: "bt25", emoji: "🧅", wordJP:"ぞう"},
{id: "bt26", emoji: "🍌", wordJP:"ぞう"},
{id: "bt27", emoji: "🥔", wordJP:"ぞう"},
{id: "bt28", emoji: "🍠", wordJP:"ぞう"},
{id: "bt29", emoji: "🥩", wordJP:"ぞう"},
{id: "bt30", emoji: "🧈", wordJP:"ぞう"},
{id: "bt31", emoji: "🥚", wordJP:"ぞう"},
{id: "bt32", emoji: "🥛", wordJP:"ぞう"},

]
