export const bakedGoodsTreatsCategory = [ 

{id: "bt1", emoji: "🥐", wordJP:"クロワッサン", kanji:""},
{id: "bt2", emoji: "🥯", wordJP:"ベーグル", kanji:""},
{id: "bt3", emoji: "🍞", wordJP:"しょくパン", kanji:"食パン"},
{id: "bt4", emoji: "🥖", wordJP:"パン", kanji:"パン"},
{id: "bt5", emoji: "🥨", wordJP:"プレッツェル", kanji:"プレッツェル"},
{id: "bt6", emoji: "🥠", wordJP:"フォーチュンクッキー", kanji:"フォーチュンクッキー"},
{id: "bt7", emoji: "🥮", wordJP:"げっぺい", kanji:"月餅"},
{id: "bt8", emoji: "🍢", wordJP:"パンダ", kanji:""},
{id: "bt9", emoji: "🍡", wordJP:"コアラ", kanji:""},
{id: "bt10", emoji: "🍧", wordJP:"とら", kanji:""},
{id: "bt11", emoji: "🍨", wordJP:"かきごおり", kanji:"かき氷"},
{id: "bt12", emoji: "🍦", wordJP:"うし", kanji:""},
{id: "bt13", emoji: "🥧", wordJP:"ライオン", kanji:""},
{id: "bt14", emoji: "🧁", wordJP:"かえる", kanji:""},
{id: "bt15", emoji: "🍰", wordJP:"さる", kanji:""},
{id: "bt16", emoji: "🎂", wordJP:"こうもり", kanji:""},
{id: "bt17", emoji: "🍮", wordJP:"おおかみ", kanji:""},
{id: "bt18", emoji: "🍭", wordJP:"いのしし", kanji:""},
{id: "bt19", emoji: "🍬", wordJP:"うま", kanji:""},
{id: "bt20", emoji: "🍫", wordJP:"かわうそ", kanji:""},
{id: "bt21", emoji: "🍿", wordJP:"やまあらし", kanji:""},
{id: "bt22", emoji: "🍘", wordJP:"ぞう", kanji:""},
{id: "bt23", emoji: "🥕", wordJP:"ぞう", kanji:""},
{id: "bt24", emoji: "🧄", wordJP:"ぞう", kanji:""},
{id: "bt25", emoji: "🧅", wordJP:"ぞう", kanji:""},
{id: "bt26", emoji: "🍌", wordJP:"ぞう", kanji:""},
{id: "bt27", emoji: "🥔", wordJP:"ぞう", kanji:""},
{id: "bt28", emoji: "🍠", wordJP:"ぞう", kanji:""},
{id: "bt29", emoji: "🥩", wordJP:"ぞう", kanji:""},
{id: "bt30", emoji: "🧈", wordJP:"ぞう", kanji:""},
{id: "bt31", emoji: "🥚", wordJP:"ぞう", kanji:""},
{id: "bt32", emoji: "🥛", wordJP:"ぞう", kanji:""},

]
