export const eatOutCategory = [ 

{id: "eo1", emoji: "🍳", wordJP:"いぬ", kanji:""},
{id: "eo2", emoji: "🥞", wordJP:"ねこ", kanji:""},
{id: "eo3", emoji: "🧇", wordJP:"ネズミ", kanji:""},
{id: "eo4", emoji: "🍗", wordJP:"ハムスター", kanji:""},
{id: "eo5", emoji: "🍖", wordJP:"ウサギ", kanji:""},
{id: "eo6", emoji: "🌭", wordJP:"キツネ", kanji:""},
{id: "eo7", emoji: "🍔", wordJP:"くま", kanji:""},
{id: "eo8", emoji: "🍟", wordJP:"パンダ", kanji:""},
{id: "eo9", emoji: "🍕", wordJP:"コアラ", kanji:""},
{id: "eo10", emoji: "🥪", wordJP:"とら", kanji:""},
{id: "eo11", emoji: "🥙", wordJP:"ライオン", kanji:""},
{id: "eo12", emoji: "🧆", wordJP:"うし", kanji:""},
{id: "eo13", emoji: "🌮", wordJP:"ライオン", kanji:""},
{id: "eo14", emoji: "🌯", wordJP:"かえる", kanji:""},
{id: "eo15", emoji: "🥗", wordJP:"さる", kanji:""},
{id: "eo16", emoji: "🥘", wordJP:"こうもり", kanji:""},
{id: "eo17", emoji: "🍝", wordJP:"おおかみ", kanji:""},
{id: "eo18", emoji: "🍜", wordJP:"いのしし", kanji:""},
{id: "eo19", emoji: "🍲", wordJP:"うま", kanji:""},
{id: "eo20", emoji: "🍛", wordJP:"かわうそ", kanji:""},
{id: "eo21", emoji: "🍣", wordJP:"やまあらし", kanji:""},
{id: "eo22", emoji: "🍱", wordJP:"ぞう", kanji:""},
{id: "eo23", emoji: "🥟", wordJP:"ぞう", kanji:""},
{id: "eo24", emoji: "🦪", wordJP:"ぞう", kanji:""},
{id: "eo25", emoji: "🍤", wordJP:"ぞう", kanji:""},
{id: "eo26", emoji: "🍙", wordJP:"ぞう", kanji:""},
{id: "eo27", emoji: "🍚", wordJP:"ぞう", kanji:""},
{id: "eo28", emoji: "🍥", wordJP:"ぞう", kanji:""},
{id: "eo29", emoji: "🥩", wordJP:"ぞう", kanji:""},
{id: "eo30", emoji: "🧈", wordJP:"ぞう", kanji:""},
{id: "eo31", emoji: "🥚", wordJP:"ぞう", kanji:""},
{id: "eo32", emoji: "🥛", wordJP:"ぞう", kanji:""},

]

