export const eatOutCategory = [ 

{id: "eo1", emoji: "🍳", wordJP:"いぬ"},
{id: "eo2", emoji: "🥞", wordJP:"ねこ"},
{id: "eo3", emoji: "🧇", wordJP:"ネズミ"},
{id: "eo4", emoji: "🍗", wordJP:"ハムスター"},
{id: "eo5", emoji: "🍖", wordJP:"ウサギ"},
{id: "eo6", emoji: "🌭", wordJP:"キツネ"},
{id: "eo7", emoji: "🍔", wordJP:"くま"},
{id: "eo8", emoji: "🍟", wordJP:"パンダ"},
{id: "eo9", emoji: "🍕", wordJP:"コアラ"},
{id: "eo10", emoji: "🥪", wordJP:"とら"},
{id: "eo11", emoji: "🥙", wordJP:"ライオン"},
{id: "eo12", emoji: "🧆", wordJP:"うし"},
{id: "eo13", emoji: "🌮", wordJP:"ライオン"},
{id: "eo14", emoji: "🌯", wordJP:"かえる"},
{id: "eo15", emoji: "🥗", wordJP:"さる"},
{id: "eo16", emoji: "🥘", wordJP:"こうもり"},
{id: "eo17", emoji: "🍝", wordJP:"おおかみ"},
{id: "eo18", emoji: "🍜", wordJP:"いのしし"},
{id: "eo19", emoji: "🍲", wordJP:"うま"},
{id: "eo20", emoji: "🍛", wordJP:"かわうそ"},
{id: "eo21", emoji: "🍣", wordJP:"やまあらし"},
{id: "eo22", emoji: "🍱", wordJP:"ぞう"},
{id: "eo23", emoji: "🥟", wordJP:"ぞう"},
{id: "eo24", emoji: "🦪", wordJP:"ぞう"},
{id: "eo25", emoji: "🍤", wordJP:"ぞう"},
{id: "eo26", emoji: "🍙", wordJP:"ぞう"},
{id: "eo27", emoji: "🍚", wordJP:"ぞう"},
{id: "eo28", emoji: "🍥", wordJP:"ぞう"},
{id: "eo29", emoji: "🥩", wordJP:"ぞう"},
{id: "eo30", emoji: "🧈", wordJP:"ぞう"},
{id: "eo31", emoji: "🥚", wordJP:"ぞう"},
{id: "eo32", emoji: "🥛", wordJP:"ぞう"},
]

