export const groceryCategory = [ 

{id: "g1", emoji: "🍎", wordJP:"いぬ"},
{id: "g2", emoji: "🍐", wordJP:"ねこ"},
{id: "g3", emoji: "🍊", wordJP:"ネズミ"},
{id: "g4", emoji: "🍋", wordJP:"ハムスター"},
{id: "g5", emoji: "🍉", wordJP:"ウサギ"},
{id: "g6", emoji: "🍇", wordJP:"キツネ"},
{id: "g7", emoji: "🍓", wordJP:"くま"},
{id: "g8", emoji: "🍈", wordJP:"パンダ"},
{id:"g9", emoji: "🍒", wordJP:"コアラ"},
{id:"g10", emoji: "🍑", wordJP:"とら"},
{id:"g11", emoji: "🥭", wordJP:"ライオン"},
{id:"g12", emoji: "🍍", wordJP:"うし"},
{id:"g13", emoji: "🥥", wordJP:"ライオン"},
{id:"g14", emoji: "🥝", wordJP:"かえる"},
{id:"g15", emoji: "🍅", wordJP:"さる"},
{id:"g16", emoji: "🍆", wordJP:"こうもり"},
{id:"g17", emoji: "🥑", wordJP:"おおかみ"},
{id:"g18", emoji: "🥦", wordJP:"いのしし"},
{id:"g19", emoji: "🥬", wordJP:"うま"},
{id:"g20", emoji: "🥒", wordJP:"かわうそ"},
{id:"g21", emoji: "🌶", wordJP:"やまあらし"},
{id:"g22", emoji: "🌽", wordJP:"ぞう"},
{id:"g23", emoji: "🥕", wordJP:"ぞう"},
{id:"g24", emoji: "🧄", wordJP:"ぞう"},
{id:"g25", emoji: "🧅", wordJP:"ぞう"},
{id:"g26", emoji: "🍌", wordJP:"ぞう"},
{id:"g27", emoji: "🥔", wordJP:"ぞう"},
{id:"g28", emoji: "🍠", wordJP:"ぞう"},
{id:"g29", emoji: "🥩", wordJP:"ぞう"},
{id:"g30", emoji: "🧈", wordJP:"ぞう"},
{id:"g31", emoji: "🥚", wordJP:"ぞう"},
{id:"g32", emoji: "🥛", wordJP:"ぞう"},
{id:"g33", emoji: "🧀", wordJP:"ぞう"},
{id:"g34", emoji: "🥓", wordJP:"ぞう"},
{id:"g35", emoji: "🥫", wordJP:"ぞう"},
{id:"g33", emoji: "🍯", wordJP:"ぞう"},
{id:"g34", emoji: "🍼", wordJP:"ぞう"},
{id:"g35", emoji: "🥫", wordJP:"ぞう"},
{id:"g35", emoji: "🍚", wordJP:"ぞう"},
]
