export const groceryCategory = [ 

{id: "g1", emoji: "🍎", wordJP:"りんご", kanji:"林檎"},
{id: "g2", emoji: "🍐", wordJP:"なし", kanji:"梨"},
{id: "g3", emoji: "🍊", wordJP:"オレンジ", kanji:"オレンジ"},
{id: "g4", emoji: "🍋", wordJP:"レモン", kanji:"檸檬"},
{id: "g5", emoji: "🍉", wordJP:"すいか", kanji:"西瓜"},
{id: "g6", emoji: "🍇", wordJP:"ぶどう", kanji:"葡萄"},
{id: "g7", emoji: "🍓", wordJP:"いちご", kanji:"苺"},
{id: "g8", emoji: "🍈", wordJP:"メロン", kanji:"メロン"},
{id:"g9", emoji: "🍒", wordJP:"さくらんぼ", kanji:"桜ん坊"},
{id:"g10", emoji: "🍑", wordJP:"もも", kanji:"桃"},
{id:"g11", emoji: "🥭", wordJP:"マンゴ", kanji:"芒果"},
{id:"g12", emoji: "🍍", wordJP:"パイナップル", kanji:"パイナップル"},
{id:"g13", emoji: "🥥", wordJP:"ココナッツ", kanji:"ココナッツ"},
{id:"g14", emoji: "🥝", wordJP:"キウイ", kanji:"キウイ"},
{id:"g15", emoji: "🍅", wordJP:"トマト", kanji:"トマト"},
{id:"g16", emoji: "🍆", wordJP:"なす", kanji:"茄子"},
{id:"g17", emoji: "🥑", wordJP:"アボカド", kanji:"アボカド"},
{id:"g18", emoji: "🥦", wordJP:"ブロコリ", kanji:"ブロコリ"},
{id:"g19", emoji: "🥬", wordJP:"レタス", kanji:"レタス"},
{id:"g20", emoji: "🥒", wordJP:"きゅうり", kanji:"胡瓜"},
{id:"g21", emoji: "🌶", wordJP:"チリペッパー", kanji:"チリペッパー"},
{id:"g22", emoji: "🌽", wordJP:"とうもろこし", kanji:"玉蜀黍"},
{id:"g23", emoji: "🥕", wordJP:"にんじん", kanji:"人参"},
{id:"g24", emoji: "🧄", wordJP:"にんにく", kanji:"大蒜"},
{id:"g25", emoji: "🧅", wordJP:"たまねぎ", kanji:"玉ねぎ"},
{id:"g26", emoji: "🍌", wordJP:"バナナ", kanji:"バナナ"},
{id:"g27", emoji: "🥔", wordJP:"じゃがいも", kanji:"じゃが芋"},
{id:"g28", emoji: "🍠", wordJP:"さつまいも", kanji:"さつま芋"},
{id:"g29", emoji: "🥩", wordJP:"にく", kanji:"肉"},
{id:"g30", emoji: "🧈", wordJP:"バター", kanji:"バター"},
{id:"g31", emoji: "🥚", wordJP:"たまご", kanji:"卵"},
{id:"g32", emoji: "🥛", wordJP:"ぎゅうにゅう", kanji:"牛乳"},
{id:"g33", emoji: "🧀", wordJP:"チーズ", kanji:"チーズ"},
{id:"g34", emoji: "🥓", wordJP:"ベーコン", kanji:"ベーコン"},
{id:"g35", emoji: "🥫", wordJP:"かんづめ", kanji:"缶詰"},
{id:"g33", emoji: "🍯", wordJP:"はちみつ", kanji:"蜂蜜"},
{id:"g34", emoji: "🍼", wordJP:"じんこうにゅう", kanji:"人工乳"},
{id:"g35", emoji: "🍚", wordJP:"こめ", kanji:"米"},

]
