export const landAnimalsCategory = [ 

{id: "la1", emoji: "🐶", wordJP:"メガネ"},
{id: "c2", emoji: "🐱", wordJP:"てにもつ"},
{id: "c3", emoji: "🐭", wordJP:"みずぎ"},
{id: "c4", emoji: "🐹", wordJP:"ブラウス"},
{id: "c5", emoji: "🐰", wordJP:"ブーツ"},
{id: "c6", emoji: "🦊", wordJP:"スパイクヒール"},
{id: "c7", emoji: "🐻", wordJP:"おうかん"},
{id: "c8", emoji: "🐼", wordJP:"コート"},
{id:"c9", emoji: "🐨", wordJP:"かさ"},
{id:"c10", emoji: "🐯", wordJP:"サングラス"},
{id:"c11", emoji: "🦁", wordJP:"くつした"},
{id:"c12", emoji: "🐮", wordJP:"ビキニ"},
{id:"c13", emoji: "🐷", wordJP:"なつぼうし"},
{id:"c14", emoji: "🐸", wordJP:"ゆびわ"},
{id:"c15", emoji: "🐵", wordJP:"スーツケース"},
{id:"c16", emoji: "🐔", wordJP:"スニーカー"},
{id:"c17", emoji: "🐧", wordJP:"くつ"},
{id:"c18", emoji: "🐦‍", wordJP:"ぼうし"},
{id:"c19", emoji: "🐥", wordJP:"ぜにぶくろ"},
{id:"c20", emoji: "🦆", wordJP:"マフラー"},
{id:"c21", emoji: "🦅", wordJP:"すいえいパンツ"},
{id:"c22", emoji: "🦉", wordJP:"シャツ"},
{id:"c23", emoji: "🦇", wordJP:"ズボン"},
{id:"c24", emoji: "🐺", wordJP:"Ｔシャツ"},
{id:"c25", emoji: "🐗", wordJP:"きもの"},
{id:"c26", emoji: "🐴", wordJP:"ドレス"},
]