export const landAnimalsCategory = [ 

{id: "la1", emoji: "🐶", wordJP:"いぬ", kanji:""},
{id: "la2", emoji: "🐱", wordJP:"ねこ", kanji:""},
{id: "la3", emoji: "🐭", wordJP:"ネズミ", kanji:""},
{id: "la4", emoji: "🐹", wordJP:"ハムスター", kanji:""},
{id: "la5", emoji: "🐰", wordJP:"ウサギ", kanji:""},
{id: "la6", emoji: "🦊", wordJP:"キツネ", kanji:""},
{id: "la7", emoji: "🐻", wordJP:"くま", kanji:""},
{id: "la8", emoji: "🐼", wordJP:"パンダ", kanji:""},
{id:"la9", emoji: "🐨", wordJP:"コアラ", kanji:""},
{id:"la10", emoji: "🐯", wordJP:"とら", kanji:""},
{id:"la11", emoji: "🦁", wordJP:"ライオン", kanji:""},
{id:"la12", emoji: "🐮", wordJP:"うし", kanji:""},
{id:"la13", emoji: "🐷", wordJP:"ライオン", kanji:""},
{id:"la14", emoji: "🐸", wordJP:"かえる", kanji:""},
{id:"la15", emoji: "🐵", wordJP:"さる", kanji:""},
{id:"la16", emoji: "🦇", wordJP:"こうもり", kanji:""},
{id:"la17", emoji: "🐺", wordJP:"おおかみ", kanji:""},
{id:"la18", emoji: "🐗", wordJP:"いのしし", kanji:""},
{id:"la19", emoji: "🐴", wordJP:"うま", kanji:""},
{id:"la20", emoji: "🦦", wordJP:"かわうそ", kanji:""},
{id:"la21", emoji: "🦔", wordJP:"やまあらし", kanji:""},
{id:"la22", emoji: "🐘", wordJP:"ぞう", kanji:""},
]